version: '3.8'

services:
    reverse-proxy:
        image: nginx:latest
        restart: unless-stopped
        container_name: reverse-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/${NGINX_CONFIG:-nginx.conf}:/etc/nginx/nginx.conf
            - ./var/log/:/var/log/nginx/
            - ./nginx/certs:/etc/nginx/certs
            - ./nginx/html:/usr/share/nginx/html
        networks:
            - shared-network

networks:
    shared-network:
        driver: bridge
        name: shared-network
